### PR TITLE
Add contributing, code of conduct and pull request template files

### PR DESCRIPTION
**Pull request by vinifarias**
## Description

This Pull Request adds the contributing, code of conduct and pull request template files.

The objective of these additions is to:
1) provide contributors with a guide to how they can contribute to GraphQL Testx project
2) create a positive social atmosphere with a healthy and constructive behavior for our community 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by wtrocki — DISMISSED** [review]
We have different format in aerogear for contributing but this is ok as well

**Comment by b1zzu** [comment]
@vinifarias  not sure we really need this level of documentation for contributing, I think this will just create a barrier to who want to contribute, too many things to read, too many things to check, this will just discourage people that would like to contribute. 

I fund many projects adding a lot of cond of conduct or contribution rules but then they completely miss: tips to debug the project, how to build and install the project locally, how to run all tests or just a single one, where to write the test, how to configure the editor to auto-format the code style and report lint errors, how to run linter locally. I believe we should focus on documenting these parts.

We can add a template for PR but I would prefer a shorter checklist like in the other aerogear projects: https://github.com/aerogear/offix/blob/master/.github/PULL_REQUEST_TEMPLATE.md
 
And we can add a short paragraph for commit message where we could just add this link: https://seesparkbox.com/foundry/semantic_commit_messages

We could need everything else only if the project will become really big.

**Comment by vinifarias** [comment]
@b1zzu I got it your points, and I'll add what you've mentioned.

But I see projects that have no standards for contributions, and members do it each in their own way, in a way that is not very clear and non-descriptive, making it difficult to keep track of what has been done and what is currently being done in the project.

My goal with this PR was to avoid this kind of problem, which for me is one of the reasons that keep the contributors away.

**Comment by b1zzu** [comment]
@vinifarias I completely understand, and I approve the `CONTRIBUTING.md` but because we are not doing anything different from many other open-source projects, I think it's easier to just paste links to external documentation and tutorial. 

For the **Code of Conduct** we can say we apply the same rule of Apache, or Mozilla

For **Pull Requests Guideline** we can link a GitHub tutorial on how to fork and create a PR

For **Git Commit Messages Style Guide** we can link this tutorial: https://seesparkbox.com/foundry/semantic_commit_messages

I'm pro for all of these paragraphs, just I wouldn't add the extensive documentation in our project because conctreally we are not doing anything different from many other projects.

**Comment by vinifarias** [comment]
@b1zzu I understand, thanks for the suggestions

**Review by b1zzu — APPROVED** [review]

**Pull request merged**
