### PR TITLE
WIP: Add master releases

### PR DESCRIPTION
**Pull request by b1zzu**
### Description

In this way we will not need to manually release the project for each small change.

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Review by wtrocki — APPROVED** [review]
Let's try it

**Comment by wtrocki** [comment]
Missing env var for this pipeline

**Comment by b1zzu** [comment]
I'm still testing it, it's not ready

**Comment by b1zzu** [comment]
In order to test it, I had to move the branch from the fork to the main repo, so I have opened a new PR #122

**Pull request closed without merging**
