### PR TITLE
Update graphback to 0.10.0-dev2 and migrate to the runtime backend

### LINKED ISSUE #66: Upgrade graphback to 0.10.x
This will help us solve these issues: #10 

And also there is a bug fix for client queries that will be released only in 0.10.x https://github.com/aerogear/graphql-testx/pull/52#discussion_r349669428

### PR DESCRIPTION
**Pull request by b1zzu**
### Description

Closes: #66 

##### Checklist

- [x] `npm test` passes
- [x] `npm run build` works
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by b1zzu** [comment]
Blocked by: https://github.com/aerogear/graphback/issues/495

**Comment by wtrocki** [comment]
This is amazing. Thank you so much for your hard work!

**Comment by vinifarias** [comment]
Awesome @b1zzu !

**Comment by b1zzu** [comment]
The too many changes to the project in the last period as forced me to rewrite this PR, a rebase was even harder: #75

**Pull request closed without merging**
